image: python:3.10

stages:
  - test
  - security
before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python -m pytest autotestlab/tests/

bandit_scan:
  stage: security
  script:
    - bandit -r autotestlab -ll